//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 05:04:06 PM GMT 
//


package com.kanke.api;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Calendar;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expenseId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "expensesId",
        "reason",
        "vatAmount",
        "amount",
        "date"
})

@XmlRootElement(name = "expenses")
@Entity
@Table(name = "expenses")
public class Expense {
    @Id
    @Column(name = "expensesId")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected int expensesId;

    @XmlElement(required = true)
    @Column(name = "reason")
    protected String reason;

    @Column(name = "amount")
    protected double amount;

    @Column(name = "vatAmount")
    protected double vatAmount;

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @Column(name = "date")
    protected Calendar date;

    /**
     * Gets the value of the expenseId property.
     */
    public int getExpenseId() {
        return expensesId;
    }

    /**
     * Sets the value of the expenseId property.
     */
    public void setExpenseId(int value) {
        this.expensesId = value;
    }

    /**
     * Gets the value of the reason property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the amount property.
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     */
    public void setAmount(double value) {
        this.amount = value;
    }


    /**
     * Gets the value of the vatAmount property.
     */
    public double getVatAmount() {
        return vatAmount;
    }

    /**
     * Sets the value of the vatAmount property.
     */
    public void setVatAmount(double value) {
        this.vatAmount = value;
    }


    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public Calendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDate(Calendar value) {
        this.date = value;
    }

}
